# Generated by Django 3.2 on 2022-10-18 14:57

import adminka.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, upload_to=adminka.models.UploadToPathAndRename('photos/'))),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('user', models.CharField(max_length=255, verbose_name='user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии',
                'db_table': 'photo',
            },
        ),
    ]
