# Generated by Django 3.2 on 2022-10-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
