# Generated by Django 3.2 on 2022-10-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0006_auto_20221021_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
